### PR TITLE
Map: filter by type, day and time

### PR DESCRIPTION
**Pull request by Valioesi**
Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/984904044

Goto /playground/karte

1) You can filter out events if it's either a collection event or if it's just signature lists. 
2) You can show only events which are today or tomorrow. This filter does not apply to events of type "signature lists", because of course they don't have a date.  
3) You can filter by three different timespans. Also only applys to collection events. 

Maybe you have to go to the dev-meetups table and adjust the endTime of collection events to test the filters. Collections events are only shown, if they end in the future. 

This is more of a suggestion in regards to how it could be done. The date and time filters for example is reeaaally basic, but maybe that's actually nicer and easier to use than a more complex one? 

Edit: I added alternatives in the comments below, if you like those options more. 
Edit 2: Does anyone have an elegant solution for mobile styling? Hiding the filters at first and only showing them upon a click on a button (a triangle thingy like in the leaderboard)?  
Edit 3: I also introduced a separate icon for collection events and a legend below the map. I would maybe want to talk regarding the icons. Is the list icon actually more fitting to the type "collection event"? That's how it is in the app, and that's also the way we wanted it, when we gave the task to schauschau. But at that point in time we (mostly I) didn't foresee that we want to have locations of type "lists" in our map (where you can just go and sign). Should we maybe switch out those icons? Or ask for a new icon for collection events and leave out our pins entirely?

### CODE REVIEW

**Comment by Valioesi** [comment]
Alternative layout: 
grafik

**Comment by Valioesi** [comment]
Alternative time checkboxes, would work similarly to day filter ("egal" deactivates the other ones)
grafik

**Review by nmauersberg — APPROVED** [review]
Cool, really nice, thank you.

Only two little things: 

-The "<EventsListed locationsFiltered={locationsFiltered} />" Component in "ShowMeetup" is always in loading state in my Preview, not sure why this happens. And I thought you wanted to exchange the icons of lists and locations?

**Comment by Valioesi** [comment]
> 

The loading thing was before I started, so shouldn't have anything to do with the pr, as far as I see. But we should def look into it.

I am waiting for D from our design agency to reply regarding creating a new icon. It's gonna be a separate task then. :)

**Pull request merged**
