### PR TITLE
Berlin spacing fixes

### PR DESCRIPTION
**Pull request by schaerta**
Links looked bad on the Berlin page, and spacing was off for the partner logos. Please check if it looks good in all browsers and screen sizes.

### CODE REVIEW

**Comment by Valioesi** [comment]
grafik

Is that wanted?

**Comment by Valioesi** [comment]
grafik

I guess not... :D

**Review by Valioesi — CHANGES_REQUESTED** [review]
Would be great if the partner logos (the images themselves) had the same margin top and bottom, so the margin does not look off on mobile. But not super important.

**Comment by schaerta** [comment]
> grafik
> 
> I guess not... :D
> 
> Edit: this is only on firefox btw, looks good on chrome

Hm, seems to be a quirk in how firefox interprets the "text-decoration: underline". Increasing the offset fixes it, so I guess I 'll do that.

**Comment by schaerta** [comment]
> Would be great if the partner logos (the images themselves) had the same margin top and bottom, so the margin does not look off on mobile. But not super important.

Do you mean the image files themselves? I can fix that in Contenful but would argue that it's not part of this PR :D

**Comment by Valioesi** [comment]
> > Would be great if the partner logos (the images themselves) had the same margin top and bottom, so the margin does not look off on mobile. But not super important.
> 
> Do you mean the image files themselves? I can fix that in Contenful but would argue that it's not part of this PR :D

Ah, I thought the pr was also about that... :)

**Review by Valioesi — APPROVED** [review]

**Pull request merged**
