### PR TITLE
Rose login page

### PR DESCRIPTION
**Pull request by Valioesi**
1) New login page
2) Rose messages for Berlin
3) Open EnterLoginCode in Modal in the SmallSignup

### CODE REVIEW

**Comment by schaerta** [comment]
The bg is now rose coloured on the main site ;)
image

**Comment by schaerta** [comment]
And this is very small on mobile:
image

But everything else looks great! Thanks a lot!

**Comment by Valioesi** [comment]
I thought about, putting the violet login component on a white background (as before), but now I just did the same as on the berlin page and made the whole section violet.

**Comment by Valioesi** [comment]
I had to add a margin to right components, because it looked weird on mobile (e.g. small signup). This now leads to a bigger margin at the end of most sections. Maybe that's not wanted...
I made the margin of components smaller than before though.

**Pull request merged**
