### PR TITLE
Fix profile tile

### PR DESCRIPTION
**Pull request by Valioesi**
Resolves: https://expedition-grundeinkommen.monday.com/boards/853311751/pulses/2206281799
Co-credits to @schaerta 

This pr tackles a few issues.

1) The profile tile was not shown on the startpage. I think we removed it on purpose, because it didn't make sense the way it was in contentful. Now we changed the way it is included in the startpage. To review this pr you need to publish "Profile Tile (Startseite) in https://app.contentful.com/spaces/af08tobnb0cl/entries/5YqifZq5dk7TPtftskcUM0?previousEntries=1Of2L0PLa8Bi0Zygk65Tch. 

2) The design was off for tablet screen sizes in the small profile tile on the municipality page. To review the fixes go to a muncipality you are signed up for.

3) After activating the profile tile on the startpage we noticed that the design was waaaay off (due to some changes in the past, it seemed). Signed in, go to the startpage and check in all screen sizes. 

4) The buttons in the profile tile did not navigate to the municipality page correctly.

### CODE REVIEW

**Comment by schaerta** [comment]
Something's still weird. Everything looks fine at first, but when I navigate from a municipality page back to the startpage, it looks like this:

image

**Comment by Valioesi** [comment]
Okay, seems like after navigating back for some reason instead of the TileNoMunicipalityLoggedInOtherMunicipality Component TileMunicipalityLoggedInOtherMunicipality is rendered. This should not be the case. And it looks weird because I did not redesign it, because it's not used anywhere.

**Comment by schaerta** [comment]
On the very smallest mobile size the 'info' box is a bit off center. Deleting 'min-width: 270px;' fixes it, so I'll do a quick commit.

image

**Comment by schaerta** [comment]
Everything else looks great and works great, so thanks, as always :)

**Review by schaerta — APPROVED** [review]

**Review by nmauersberg — APPROVED** [review]
Cool, thank you. Works well for me too. I like, that we were now only render two municipalities. :D

**Comment by Valioesi** [comment]
Perfect, thanks, @schaerta

**Pull request merged**
